trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'windows-latest'

stages:
- stage: Build
  jobs:
  - job: Build
    pool: 
      vmImage: $(vmImageName)
    steps:
    - task: NodeTool@0
      inputs:
        versionSource: 'spec'
        versionSpec: '6.x'
        checkLatest: true

    - script: npm install
      displayName: 'Install dependencies'

    - script: npm run build
      displayName: 'Build TypeScript App'

    - task: ArchiveFiles@2
      condition: succeeded()
      inputs:
        rootFolderOrFile: '$(Build.BinariesDirectory)'
        includeRootFolder: true
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        replaceExistingArchive: true

