trigger:
- main

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '73c5936f-f7ef-4b24-b1e4-a5bc1fa286ae'
  imageRepository: 'angularimage'
  containerRegistry: 'burakacr1.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'windows-latest'

stages:
- stage: Build
  jobs:
  - job: Build
    pool: 
      vmImage: $(vmImageName)
    steps:
    - task: NodeTool@0
      inputs:
        versionSource: 'spec'
        versionSpec: '6.x'
        checkLatest: true

    - script: npm install
      displayName: 'Install dependencies'

    - script: npm run build
      displayName: 'Build TypeScript App'

    - task: ArchiveFiles@2
      condition: succeeded()
      inputs:
        rootFolderOrFile: '$(Build.BinariesDirectory)'
        includeRootFolder: true
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        replaceExistingArchive: true

    - task: PublishBuildArtifacts@1
      condition: succeeded()
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: '$(tag)'
        publishLocation: 'Container'